backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/photos/originals" # Media files will be stored in the repo under images/uploads
public_folder: "/photos/originals" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "images" # Used in routes, e.g., /admin/collections/blog
    label: "Images" # Used in the UI
    folder: "photos/originals" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Featured Image", name: "thumbnail", widget: "image"}